# -*- coding: utf-8 -*-
"""aula0902

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmlaOAgK6h8Zm7H-nnu5m5nrx5oXdMJ2
"""

def altera_lista(lst):
  lst.append(99)

def reatribui_int(x):
  x = 10
  print(x)

v = [1, 2]
num = 5

altera_lista(v)
reatribui_int(num)

print(v)
print(num)

for i in range(5):
  print(i)

def fatorial(n):
  if n == 0:
    return 1
  else:
    fat = 1
    for i in range(1, n + 1):
      fat *= i

    return fat

nome = input("Digite seu nome: ")
print(nome)

num1 = float(input("Qual o primeiro número? "))
operacao = input("Qual operação quer realizar: +, -, * || /: ")
num2 = float(input("Qual o segundo número? "))
if operacao == "+":
    print(num1 + num2)
elif operacao == "-":
    print(num1 - num2)
elif operacao == "*":
    print(num1 * num2)
elif operacao == "/":
    print(num1 / num2)